<a href="https://colab.research.google.com/github/DrAyesha91/Nasscom-fdp-/blob/main/D3_Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

# Your code for Task 1 here:
s1_1 = pd.Series([10, 20, 30, 40, 50])
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("s1_1:")
display(s1_1)
print("np_array1_2:")
display(np_array1_2)
print("df1_3:")
display(df1_3)

# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

# Your code for Task 2 here:
num_rows = 100
dates = pd.date_range(start='2023-01-01', end='2023-04-09', periods=num_rows)
regions = np.random.choice(['East', 'West', 'North', 'South'], size=num_rows)
products = np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=num_rows)
sales = np.random.randint(100, 1001, size=num_rows)
quantity = np.random.randint(1, 11, size=num_rows)

df_sales = pd.DataFrame({
    'Date': dates,
    'Region': regions,
    'Product': products,
    'Sales': sales,
    'Quantity': quantity
})

# Introduce NaN values
sales_nan_indices = np.random.choice(df_sales.index, 5, replace=False)
quantity_nan_indices = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[sales_nan_indices, 'Sales'] = np.nan
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print("df_sales (with NaNs):")
display(df_sales.head())
display(df_sales.tail())

# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.

# Your code for Task 3 here:
df3_1 = df_sales[['Region', 'Sales']]
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]

# Using .loc
val3_4_loc = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]
# Using .iloc (find the index first)
monitor_indices = df_sales[df_sales['Product'] == 'Monitor'].index
val3_4_iloc = df_sales.iloc[monitor_indices[0]]['Sales']

# For simplicity, store one of them in val3_4 as requested
val3_4 = val3_4_loc

print("df3_1 (Region and Sales):")
display(df3_1.head())
print("df3_2 (Product is Laptop):")
display(df3_2.head())
print("df3_3 (Region is East AND Sales > 500):")
display(df3_3.head())
print(f"val3_4 (First Sales value where Product is Monitor): {val3_4}")

# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

# Your code for Task 4 here:
missing_counts4_1 = df_sales.isnull().sum()

# Create a copy to avoid modifying original df_sales directly for subsequent steps
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())

df4_3_dropped = df_sales.dropna()

print("missing_counts4_1:")
display(missing_counts4_1)
print("df4_2_filled (Sales NaNs filled with mean):")
display(df4_2_filled.head())
print("df4_3_dropped (Rows with any NaNs dropped):")
display(df4_3_dropped.head())

# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.

# Your code for Task 5 here:
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])

df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("df_sales with 'Total_Revenue' column:")
display(df_sales.head())
print("df5_2_sorted (Sorted by Date and Sales):")
display(df5_2_sorted.head())
print("df5_3_grouped_region (Sum of Sales and Quantity by Region):")
display(df5_3_grouped_region)
print("df5_4_grouped_product (Average Sales by Product):")
display(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
s1_1:

0    10
1    20
2    30
3    40
4    50
dtype: int64

np_array1_2:

array([[63, 71, 54, 25],
       [72, 66,  6, 11],
       [53, 22, 78, 71]])

df1_3:

    A   B   C   D
0  63  71  54  25
1  72  66   6  11
2  53  22  78  71

--- Task 2: Synthetic Data Generation for Practice ---
df_sales (with NaNs):

                           Date Region   Product  Sales  Quantity
0 2023-01-01 00:00:00.000000000   East    Laptop  263.0       7.0
1 2023-01-01 23:45:27.272727272  South  Keyboard  210.0       9.0
2 2023-01-02 23:30:54.545454545   West  Keyboard  712.0       7.0
3 2023-01-03 23:16:21.818181818  North   Monitor  585.0       6.0
4 2023-01-04 23:01:49.090909090  North     Mouse  880.0       9.0

                            Date Region   Product  Sales  Quantity
95 2023-04-05 00:58:10.909090910  North     Mouse  514.0       6.0
96 2023-04-06 00:43:38.181818182  North  Keyboard  632.0       3.0
97 2023-04-07 00:29:05.454545455   West    Laptop  691.0       5.0
98 2023-04-08 00:14:32.727272728   East     Mouse  822.0       8.0
99 2023-04-09 00:00:00.000000000  North    Laptop  445.0       5.0

--- Task 3: Indexing and Slicing in DataFrames ---
df3_1 (Region and Sales):

  Region  Sales
0   East  263.0
1  South  210.0
2   West  712.0
3  North  585.0
4  North  880.0

df3_2 (Product is Laptop):

                            Date Region Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000   East  Laptop  263.0       7.0
5  2023-01-05 22:47:16.363636363   East  Laptop  627.0       7.0
6  2023-01-06 22:32:43.636363636  North  Laptop  493.0       1.0
7  2023-01-07 22:18:10.909090909   West  Laptop  468.0       2.0
11 2023-01-11 21:20:00.000000000  North  Laptop  557.0      10.0

df3_3 (Region is East AND Sales > 500):

                            Date Region   Product  Sales  Quantity
5  2023-01-05 22:47:16.363636363   East    Laptop  627.0       7.0
12 2023-01-12 21:05:27.272727272   East  Keyboard  707.0       9.0
13 2023-01-13 20:50:54.545454545   East     Mouse  966.0      10.0
24 2023-01-24 18:10:54.545454545   East     Mouse  792.0       1.0
42 2023-02-11 13:49:05.454545455   East   Monitor  871.0      10.0

val3_4 (First Sales value where Product is Monitor): 585.0

--- Task 4: Data Cleaning (Handling Missing Values) ---
missing_counts4_1:

Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

df4_2_filled (Sales NaNs filled with mean):

                           Date Region   Product  Sales  Quantity
0 2023-01-01 00:00:00.000000000   East    Laptop  263.0       7.0
1 2023-01-01 23:45:27.272727272  South  Keyboard  210.0       9.0
2 2023-01-02 23:30:54.545454545   West  Keyboard  712.0       7.0
3 2023-01-03 23:16:21.818181818  North   Monitor  585.0       6.0
4 2023-01-04 23:01:49.090909090  North     Mouse  880.0       9.0

df4_3_dropped (Rows with any NaNs dropped):

                           Date Region   Product  Sales  Quantity
0 2023-01-01 00:00:00.000000000   East    Laptop  263.0       7.0
1 2023-01-01 23:45:27.272727272  South  Keyboard  210.0       9.0
2 2023-01-02 23:30:54.545454545   West  Keyboard  712.0       7.0
3 2023-01-03 23:16:21.818181818  North   Monitor  585.0       6.0
4 2023-01-04 23:01:49.090909090  North     Mouse  880.0       9.0

--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---
df_sales with 'Total_Revenue' column:

,Date,Region,Product,Sales,Quantity,Total_Revenue
0,2023-01-01 00:00:00.000000000,East,Laptop,263.0,7.0,1841.0
1,2023-01-01 23:45:27.272727272,South,Keyboard,210.0,9.0,1890.0
2,2023-01-02 23:30:54.545454545,West,Keyboard,712.0,7.0,4984.0
3,2023-01-03 23:16:21.818181818,North,Monitor,585.0,6.0,3510.0
4,2023-01-04 23:01:49.090909090,North,Mouse,880.0,9.0,7920.0

df5_2_sorted (Sorted by Date and Sales):

,Date,Region,Product,Sales,Quantity,Total_Revenue
0,2023-01-01 00:00:00.000000000,East,Laptop,263.0,7.0,1841.0
1,2023-01-01 23:45:27.272727272,South,Keyboard,210.0,9.0,1890.0
2,2023-01-02 23:30:54.545454545,West,Keyboard,712.0,7.0,4984.0
3,2023-01-03 23:16:21.818181818,North,Monitor,585.0,6.0,3510.0
4,2023-01-04 23:01:49.090909090,North,Mouse,880.0,9.0,7920.0

df5_3_grouped_region (Sum of Sales and Quantity by Region):

          Sales  Quantity
Region
East    11333.0     116.0
North   15442.0     169.0
South   13858.0     127.0
West    11763.0     137.0

df5_4_grouped_product (Average Sales by Product):

Product
Keyboard    482.619048
Laptop      553.391304
Monitor     605.500000
Mouse       546.913043
Name: Sales, dtype: float64